<?php require_once ('../App/Views/layout/header.phtml'); ?>
<div class="container">
    <form name="form-filtro" method="post" action="http://scempme.abgf.gov.br/abgf/exportador/analisalimite" class="clearfix">
        <input type="hidden" name="_token" value="qavGb4l5scThkPfBQmXc0XnkdQQdhzAY0aVW4FbP">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Filtrar operação</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Nº da Operação</label>
                            <input type="text" maxlength="10" name="cod_unico_operacao" id="cod_unico_operacao" value="" class="form-control">
                        </div>
                    </div>



                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Status da operação</label>
                            <select class="form-control input-sm" name="st_oper" id="st_oper">
                                <option value="0">Selecione</option>
                                <option value="12">AGUARDANDO BOLETO DE PAGAMENTO</option>
                                <option value="13">AGUARDANDO COMPROVANTE DE PAGAMENTO</option>
                                <option value="5">APROVADA</option>
                                <option value="10">CANCELADA</option>
                                <option value="3">EM ANÁLISE</option>
                                <option value="14">EXCLUÍDA</option>
                                <option value="9">INDEFERIDA</option>
                                <option value="16">INSERÇÃO DE BOLETO RELATORIO D&amp;B</option>
                                <option value="15">INSERÇÃO DE COMPROVANTE RELATORIO D&amp;B</option>
                                <option value="21">NÃO HÁ LIMITE DISPONÍVEL</option>
                                <option value="20">VERIFICAÇÃO DE DISPONIBILIDADE DE LIMITE NA ABGF</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Modalidade da operação</label>
                            <select class="form-control input-sm" name="id_modalidade" id="id_modalidade">
                                <option value="0">Selecione</option>
                                <option value="1">PRÉ-EMBARQUE</option>
                                <option value="2">PRÉ+PÓS-EMBARQUE</option>
                                <option value="3">PÓS-EMBARQUE</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Total por página</label>
                            <select class="form-control input-sm" name="total_paginacao" id="total_paginacao"><option value="10">10</option><option value="50">50</option><option value="100">100</option><option value="500">500</option><option value="-1">Todas</option></select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <button id="btnPesquisar" name="btnPesquisar" type="submit" class="btn btn-success pull-right" style="margin-right: 10px;">
                        <i class="fa fa-filter"></i> Filtrar operação
                    </button>
                    <button id="btnReset" name="btnReset" type="reset" class="btn btn-default pull-right" style="margin-right: 10px;" onclick="window.location.href = ' http://scempme.abgf.gov.br/abgf/exportador/analisalimite '">
                        <i class="fa fa-filter"></i> Limpar filtro
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
<?php require_once ('../App/Views/layout/footer.phtml'); ?>




