<div class="container">
    <form name="formCartorios" id="formCartorios" method="post" action="" class="clearfix">
        <input type="hidden" name="id" id="id" value="0">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Importar Cartórios Excel</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Nome</label>
                            <input type="text" name="nome" id="nome" value="" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Razão</label>
                            <input type="text" name="razao" id="razao" value="" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">

                            <button id="btnCadastrar" name="btnCadastrar" type="button" class="btn btn-success " style="margin-top: 10px;">
                                Importar cartórios
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>